#!/bin/bash

# gofmt has exit status 0 when there is unformatted code, so we need to test
# whether the standard output is a non-empty string.
CMD='gofmt -l .'
echo $CMD
output=$($CMD)
exit_status=$?
if test $output; then
  echo -e 'The files below are not correctly formatted.' \
    "Please run go fmt.\n$output"
  exit 1
fi
if [[ $exit_status != 0 ]]; then
  exit $exit_status
fi

CMD='go vet'
echo $CMD
if ! $CMD; then
  exit 1
fi

CMD='revive -set_exit_status'
echo $CMD
if ! $CMD; then
  exit 1
fi

CMD='staticcheck'
echo $CMD
if ! $CMD; then
  exit 1
fi

CMD='errcheck'
echo $CMD
if ! $CMD; then
  exit 1
fi

CMD='go test'
echo $CMD
if ! $CMD; then
  exit 1
fi

outfile=$1
if [[ $outfile == '' ]]; then
  outfile=server
fi

CMD="go build -o $outfile ."
echo $CMD
if ! $CMD; then
  exit 1
fi
